# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1bfb615d6837e45ae34fb39a820c62ca"
name = "ShopDelta"
application_url = "https://shop-delta2.vercel.app/"
embedded = true
handle = "shopdelta"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_orders,write_products"

[auth]
redirect_urls = [
  "https://shop-delta2.vercel.app/auth/callback",
  "https://shop-delta2.vercel.app/auth/shopify/callback",
  "https://shop-delta2.vercel.app/api/auth/callback"
]

[pos]
embedded = false
